server:
  context-path: /springBootMvc
  port: 8082

spring:
  messages:
    basename: i18n
  devtools:
    restart:
      additional-paths: src/main/
  thymeleaf:
    prefix: templates/views/
    suffix: .html

  datasource:
      url: jdbc:mysql://localhost:3306/SpringBootMvc
      username: sa
      password: sa
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 50
      max-wait: 10000
  jpa:
      hibernate:
        ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      show-sql: true
      database: MYSQL
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
security:
  user:
    name: admin
    password: admin
  basic:
    realm: springBootMvc